/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config Defaults
         * @description Return a fresh PPAConfig with engine defaults, used to seed the UI form.
         */
        get: operations["config_defaults_api_config_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Config Validate
         * @description Run the engine's domain validation on the submitted config.
         *
         *     Pydantic handles per-field bounds at parse time; this endpoint additionally
         *     runs `PPAConfig.validate()` which checks cross-field invariants (e.g. that
         *     deal.start_date is strictly before deal.end_date).
         *
         *     Returns the validated config unchanged on success; 422 with the engine's
         *     error message on failure.
         */
        post: operations["config_validate_api_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Central Profiles
         * @description Generate the central-scenario hourly profiles over the full deal horizon.
         *
         *     Returns three aligned series (solar production, market price, consumer load)
         *     at the seeds configured in `config.solar.seed` and `config.market.seed`.
         *
         *     Payload size at default config: ~87,600 hourly rows × 3 series.
         */
        post: operations["central_profiles_api_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Central Scenario */
        post: operations["preview_central_scenario_api_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/valuation/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Valuation Matrix */
        post: operations["valuation_matrix_api_valuation_matrix_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Simulation */
        post: operations["run_simulation_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solver/negotiation-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Negotiation Range */
        post: operations["negotiation_range_api_solver_negotiation_range_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solver/tornado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tornado */
        post: operations["tornado_api_solver_tornado_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solver/fair-strike": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fair Strike */
        post: operations["fair_strike_api_solver_fair_strike_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComboRiskSummarySchema */
        ComboRiskSummarySchema: {
            /** Supply Structure */
            supply_structure: string;
            /** Pricing Structure */
            pricing_structure: string;
            /** Central Producer Npv */
            central_producer_npv: number;
            /** Central Capture Rate */
            central_capture_rate: number;
            joint: components["schemas"]["PathDistributionSchema"];
            price_only: components["schemas"]["PathDistributionSchema"];
            volume_only: components["schemas"]["PathDistributionSchema"];
            variance_decomp: components["schemas"]["VarianceDecompositionSchema"];
        };
        /** ConsumerLoadConfigSchema */
        ConsumerLoadConfigSchema: {
            /**
             * Annual Consumption Gwh
             * @default 100
             */
            annual_consumption_gwh: number;
            /**
             * Seasonal Amplitude
             * @default 0.15
             */
            seasonal_amplitude: number;
            /**
             * Seasonal Peak Day
             * @default 15
             */
            seasonal_peak_day: number;
            /**
             * Weekday Hourly Shape
             * @default [
             *       0.55,
             *       0.5,
             *       0.48,
             *       0.48,
             *       0.52,
             *       0.62,
             *       0.78,
             *       0.9,
             *       0.98,
             *       1.02,
             *       1.1,
             *       1.06,
             *       1,
             *       1.02,
             *       1,
             *       1.02,
             *       1.05,
             *       1.08,
             *       1.1,
             *       1.04,
             *       0.92,
             *       0.8,
             *       0.7,
             *       0.6
             *     ]
             */
            weekday_hourly_shape: number[];
            /**
             * Weekend Hourly Shape
             * @default [
             *       0.55,
             *       0.5,
             *       0.48,
             *       0.48,
             *       0.5,
             *       0.58,
             *       0.68,
             *       0.78,
             *       0.85,
             *       0.9,
             *       0.92,
             *       0.9,
             *       0.88,
             *       0.85,
             *       0.83,
             *       0.83,
             *       0.85,
             *       0.88,
             *       0.88,
             *       0.83,
             *       0.75,
             *       0.68,
             *       0.62,
             *       0.58
             *     ]
             */
            weekend_hourly_shape: number[];
            /**
             * Noise Sigma
             * @default 0.05
             */
            noise_sigma: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** DealConfigSchema */
        DealConfigSchema: {
            /**
             * Start Date
             * @default 2027-01-01
             */
            start_date: string;
            /**
             * End Date
             * @default 2036-12-31
             */
            end_date: string;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /**
             * Discount Rate
             * @default 0.06
             */
            discount_rate: number;
        };
        /** FairStrikeRequest */
        FairStrikeRequest: {
            /**
             * @default {
             *       "location": {
             *         "altitude": 10,
             *         "lat": 52.1,
             *         "lon": 5.1,
             *         "tz": "Europe/Amsterdam"
             *       },
             *       "solar": {
             *         "azimuth_deg": 180,
             *         "capacity_mw": 50,
             *         "cloud_factor_logit_scale": 0.7,
             *         "cloud_factor_phi": 0.9,
             *         "degradation_rate": 0.005,
             *         "monthly_cloud_means": [
             *           0.38,
             *           0.42,
             *           0.5,
             *           0.57,
             *           0.63,
             *           0.68,
             *           0.68,
             *           0.65,
             *           0.58,
             *           0.5,
             *           0.42,
             *           0.36
             *         ],
             *         "performance_ratio": 0.8,
             *         "seed": 42,
             *         "tilt_deg": 35
             *       },
             *       "market": {
             *         "ar1_phi": 0.7,
             *         "ar1_sigma": 8,
             *         "base_price": 83,
             *         "beta_wind_2027": 35,
             *         "beta_wind_2036": 75,
             *         "cannibalisation_alpha_2027": 40,
             *         "cannibalisation_alpha_2036": 60,
             *         "demand_peak_day": 15,
             *         "demand_weekday_shape": [
             *           -10,
             *           -12,
             *           -14,
             *           -14,
             *           -12,
             *           -10,
             *           -8,
             *           8,
             *           20,
             *           18,
             *           15,
             *           13,
             *           11,
             *           10,
             *           10,
             *           12,
             *           18,
             *           35,
             *           30,
             *           22,
             *           14,
             *           5,
             *           0,
             *           -8
             *         ],
             *         "demand_weekend_shape": [
             *           -12,
             *           -14,
             *           -16,
             *           -16,
             *           -14,
             *           -12,
             *           -10,
             *           -5,
             *           2,
             *           5,
             *           8,
             *           9,
             *           9,
             *           8,
             *           8,
             *           8,
             *           9,
             *           10,
             *           12,
             *           10,
             *           6,
             *           2,
             *           -2,
             *           -10
             *         ],
             *         "demand_winter_uplift": 0.15,
             *         "drift": -1.5,
             *         "monthly_wind_means": [
             *           0.42,
             *           0.4,
             *           0.38,
             *           0.33,
             *           0.28,
             *           0.25,
             *           0.24,
             *           0.25,
             *           0.3,
             *           0.36,
             *           0.4,
             *           0.43
             *         ],
             *         "production_cannibalisation_correlation": 0.65,
             *         "seasonal_amplitude": 15,
             *         "seasonal_peak_day": 15,
             *         "seed": 42,
             *         "system_solar_altitude": 10,
             *         "system_solar_azimuth_deg": 180,
             *         "system_solar_lat": 51.6,
             *         "system_solar_lon": 5.3,
             *         "system_solar_tilt_deg": 30,
             *         "system_solar_tz": "Europe/Amsterdam",
             *         "wind_cf_logit_scale": 0.6,
             *         "wind_cf_phi": 0.95,
             *         "wind_diurnal_logit_adder": [
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.08,
             *           0.05,
             *           0.02,
             *           -0.02,
             *           -0.05,
             *           -0.07,
             *           -0.09,
             *           -0.1,
             *           -0.1,
             *           -0.09,
             *           -0.07,
             *           -0.05,
             *           -0.02,
             *           0.02,
             *           0.05,
             *           0.07,
             *           0.08,
             *           0.1,
             *           0.1
             *         ],
             *         "wind_reference_cf": 0.33,
             *         "wind_seed": 43
             *       },
             *       "load": {
             *         "annual_consumption_gwh": 100,
             *         "noise_sigma": 0.05,
             *         "seasonal_amplitude": 0.15,
             *         "seasonal_peak_day": 15,
             *         "seed": 42,
             *         "weekday_hourly_shape": [
             *           0.55,
             *           0.5,
             *           0.48,
             *           0.48,
             *           0.52,
             *           0.62,
             *           0.78,
             *           0.9,
             *           0.98,
             *           1.02,
             *           1.1,
             *           1.06,
             *           1,
             *           1.02,
             *           1,
             *           1.02,
             *           1.05,
             *           1.08,
             *           1.1,
             *           1.04,
             *           0.92,
             *           0.8,
             *           0.7,
             *           0.6
             *         ],
             *         "weekend_hourly_shape": [
             *           0.55,
             *           0.5,
             *           0.48,
             *           0.48,
             *           0.5,
             *           0.58,
             *           0.68,
             *           0.78,
             *           0.85,
             *           0.9,
             *           0.92,
             *           0.9,
             *           0.88,
             *           0.85,
             *           0.83,
             *           0.83,
             *           0.85,
             *           0.88,
             *           0.88,
             *           0.83,
             *           0.75,
             *           0.68,
             *           0.62,
             *           0.58
             *         ]
             *       },
             *       "deal": {
             *         "currency": "EUR",
             *         "discount_rate": 0.06,
             *         "end_date": "2036-12-31",
             *         "start_date": "2027-01-01"
             *       }
             *     }
             */
            config: components["schemas"]["PPAConfigSchema"];
            /**
             * Structure A
             * @default pay_as_produced
             * @enum {string}
             */
            structure_a: "pay_as_produced" | "pay_as_nominated" | "baseload";
            /**
             * Structure B
             * @default baseload
             * @enum {string}
             */
            structure_b: "pay_as_produced" | "pay_as_nominated" | "baseload";
            /**
             * Pricing Structure
             * @default fixed_flat
             * @enum {string}
             */
            pricing_structure: "fixed_flat" | "fixed_escalated";
            /**
             * Strike A
             * @default 65
             */
            strike_a: number;
            /**
             * N Paths
             * @default 200
             */
            n_paths: number;
        };
        /** FairStrikeResultSchema */
        FairStrikeResultSchema: {
            /** Structure A */
            structure_a: string;
            /** Structure B */
            structure_b: string;
            /** Strike A */
            strike_a: number;
            /** Fair Strike B */
            fair_strike_b: number;
            /** P50 Npv A */
            p50_npv_a: number;
            /** P50 Npv B */
            p50_npv_b: number;
            /** Pricing Structure */
            pricing_structure: string;
            /** N Paths */
            n_paths: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocationConfigSchema */
        LocationConfigSchema: {
            /**
             * Lat
             * @default 52.1
             */
            lat: number;
            /**
             * Lon
             * @default 5.1
             */
            lon: number;
            /**
             * Tz
             * @default Europe/Amsterdam
             */
            tz: string;
            /**
             * Altitude
             * @default 10
             */
            altitude: number;
        };
        /** MarketPriceConfigSchema */
        MarketPriceConfigSchema: {
            /**
             * Base Price
             * @default 83
             */
            base_price: number;
            /**
             * Drift
             * @default -1.5
             */
            drift: number;
            /**
             * Seasonal Amplitude
             * @default 15
             */
            seasonal_amplitude: number;
            /**
             * Seasonal Peak Day
             * @default 15
             */
            seasonal_peak_day: number;
            /**
             * Demand Weekday Shape
             * @default [
             *       -10,
             *       -12,
             *       -14,
             *       -14,
             *       -12,
             *       -10,
             *       -8,
             *       8,
             *       20,
             *       18,
             *       15,
             *       13,
             *       11,
             *       10,
             *       10,
             *       12,
             *       18,
             *       35,
             *       30,
             *       22,
             *       14,
             *       5,
             *       0,
             *       -8
             *     ]
             */
            demand_weekday_shape: number[];
            /**
             * Demand Weekend Shape
             * @default [
             *       -12,
             *       -14,
             *       -16,
             *       -16,
             *       -14,
             *       -12,
             *       -10,
             *       -5,
             *       2,
             *       5,
             *       8,
             *       9,
             *       9,
             *       8,
             *       8,
             *       8,
             *       9,
             *       10,
             *       12,
             *       10,
             *       6,
             *       2,
             *       -2,
             *       -10
             *     ]
             */
            demand_weekend_shape: number[];
            /**
             * Demand Winter Uplift
             * @default 0.15
             */
            demand_winter_uplift: number;
            /**
             * Demand Peak Day
             * @default 15
             */
            demand_peak_day: number;
            /**
             * Monthly Wind Means
             * @default [
             *       0.42,
             *       0.4,
             *       0.38,
             *       0.33,
             *       0.28,
             *       0.25,
             *       0.24,
             *       0.25,
             *       0.3,
             *       0.36,
             *       0.4,
             *       0.43
             *     ]
             */
            monthly_wind_means: number[];
            /**
             * Wind Diurnal Logit Adder
             * @default [
             *       0.1,
             *       0.1,
             *       0.1,
             *       0.1,
             *       0.1,
             *       0.08,
             *       0.05,
             *       0.02,
             *       -0.02,
             *       -0.05,
             *       -0.07,
             *       -0.09,
             *       -0.1,
             *       -0.1,
             *       -0.09,
             *       -0.07,
             *       -0.05,
             *       -0.02,
             *       0.02,
             *       0.05,
             *       0.07,
             *       0.08,
             *       0.1,
             *       0.1
             *     ]
             */
            wind_diurnal_logit_adder: number[];
            /**
             * Wind Cf Phi
             * @default 0.95
             */
            wind_cf_phi: number;
            /**
             * Wind Cf Logit Scale
             * @default 0.6
             */
            wind_cf_logit_scale: number;
            /**
             * Wind Reference Cf
             * @default 0.33
             */
            wind_reference_cf: number;
            /**
             * Beta Wind 2027
             * @default 35
             */
            beta_wind_2027: number;
            /**
             * Beta Wind 2036
             * @default 75
             */
            beta_wind_2036: number;
            /**
             * Wind Seed
             * @default 43
             */
            wind_seed: number;
            /**
             * Cannibalisation Alpha 2027
             * @default 40
             */
            cannibalisation_alpha_2027: number;
            /**
             * Cannibalisation Alpha 2036
             * @default 60
             */
            cannibalisation_alpha_2036: number;
            /**
             * Production Cannibalisation Correlation
             * @default 0.65
             */
            production_cannibalisation_correlation: number;
            /**
             * System Solar Lat
             * @default 51.6
             */
            system_solar_lat: number;
            /**
             * System Solar Lon
             * @default 5.3
             */
            system_solar_lon: number;
            /**
             * System Solar Tz
             * @default Europe/Amsterdam
             */
            system_solar_tz: string;
            /**
             * System Solar Altitude
             * @default 10
             */
            system_solar_altitude: number;
            /**
             * System Solar Tilt Deg
             * @default 30
             */
            system_solar_tilt_deg: number;
            /**
             * System Solar Azimuth Deg
             * @default 180
             */
            system_solar_azimuth_deg: number;
            /**
             * Ar1 Phi
             * @default 0.7
             */
            ar1_phi: number;
            /**
             * Ar1 Sigma
             * @default 8
             */
            ar1_sigma: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** MonteCarloPathRow */
        MonteCarloPathRow: {
            /** Mode */
            mode: string;
            /** Path */
            path: number;
            /** Supply Structure */
            supply_structure: string;
            /** Pricing Structure */
            pricing_structure: string;
            /** Producer Npv */
            producer_npv: number;
            /** Consumer Npv */
            consumer_npv: number;
            /** Total Volume Mwh */
            total_volume_mwh: number;
            /** Average Strike Eur Mwh */
            average_strike_eur_mwh: number;
            /** Capture Rate */
            capture_rate: number;
            /** Volume Value */
            volume_value: number;
            /** Profile Value */
            profile_value: number;
        };
        /** MonteCarloResponse */
        MonteCarloResponse: {
            /** Paths */
            paths: components["schemas"]["MonteCarloPathRow"][];
            /** Central Rows */
            central_rows: components["schemas"]["ValuationRowSchema"][];
            risk_summary: components["schemas"]["RiskSummarySchema"];
            /** N Paths */
            n_paths: number;
            /** Base Strike */
            base_strike: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
        };
        /** NegotiationRangeRequest */
        NegotiationRangeRequest: {
            /**
             * @default {
             *       "location": {
             *         "altitude": 10,
             *         "lat": 52.1,
             *         "lon": 5.1,
             *         "tz": "Europe/Amsterdam"
             *       },
             *       "solar": {
             *         "azimuth_deg": 180,
             *         "capacity_mw": 50,
             *         "cloud_factor_logit_scale": 0.7,
             *         "cloud_factor_phi": 0.9,
             *         "degradation_rate": 0.005,
             *         "monthly_cloud_means": [
             *           0.38,
             *           0.42,
             *           0.5,
             *           0.57,
             *           0.63,
             *           0.68,
             *           0.68,
             *           0.65,
             *           0.58,
             *           0.5,
             *           0.42,
             *           0.36
             *         ],
             *         "performance_ratio": 0.8,
             *         "seed": 42,
             *         "tilt_deg": 35
             *       },
             *       "market": {
             *         "ar1_phi": 0.7,
             *         "ar1_sigma": 8,
             *         "base_price": 83,
             *         "beta_wind_2027": 35,
             *         "beta_wind_2036": 75,
             *         "cannibalisation_alpha_2027": 40,
             *         "cannibalisation_alpha_2036": 60,
             *         "demand_peak_day": 15,
             *         "demand_weekday_shape": [
             *           -10,
             *           -12,
             *           -14,
             *           -14,
             *           -12,
             *           -10,
             *           -8,
             *           8,
             *           20,
             *           18,
             *           15,
             *           13,
             *           11,
             *           10,
             *           10,
             *           12,
             *           18,
             *           35,
             *           30,
             *           22,
             *           14,
             *           5,
             *           0,
             *           -8
             *         ],
             *         "demand_weekend_shape": [
             *           -12,
             *           -14,
             *           -16,
             *           -16,
             *           -14,
             *           -12,
             *           -10,
             *           -5,
             *           2,
             *           5,
             *           8,
             *           9,
             *           9,
             *           8,
             *           8,
             *           8,
             *           9,
             *           10,
             *           12,
             *           10,
             *           6,
             *           2,
             *           -2,
             *           -10
             *         ],
             *         "demand_winter_uplift": 0.15,
             *         "drift": -1.5,
             *         "monthly_wind_means": [
             *           0.42,
             *           0.4,
             *           0.38,
             *           0.33,
             *           0.28,
             *           0.25,
             *           0.24,
             *           0.25,
             *           0.3,
             *           0.36,
             *           0.4,
             *           0.43
             *         ],
             *         "production_cannibalisation_correlation": 0.65,
             *         "seasonal_amplitude": 15,
             *         "seasonal_peak_day": 15,
             *         "seed": 42,
             *         "system_solar_altitude": 10,
             *         "system_solar_azimuth_deg": 180,
             *         "system_solar_lat": 51.6,
             *         "system_solar_lon": 5.3,
             *         "system_solar_tilt_deg": 30,
             *         "system_solar_tz": "Europe/Amsterdam",
             *         "wind_cf_logit_scale": 0.6,
             *         "wind_cf_phi": 0.95,
             *         "wind_diurnal_logit_adder": [
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.08,
             *           0.05,
             *           0.02,
             *           -0.02,
             *           -0.05,
             *           -0.07,
             *           -0.09,
             *           -0.1,
             *           -0.1,
             *           -0.09,
             *           -0.07,
             *           -0.05,
             *           -0.02,
             *           0.02,
             *           0.05,
             *           0.07,
             *           0.08,
             *           0.1,
             *           0.1
             *         ],
             *         "wind_reference_cf": 0.33,
             *         "wind_seed": 43
             *       },
             *       "load": {
             *         "annual_consumption_gwh": 100,
             *         "noise_sigma": 0.05,
             *         "seasonal_amplitude": 0.15,
             *         "seasonal_peak_day": 15,
             *         "seed": 42,
             *         "weekday_hourly_shape": [
             *           0.55,
             *           0.5,
             *           0.48,
             *           0.48,
             *           0.52,
             *           0.62,
             *           0.78,
             *           0.9,
             *           0.98,
             *           1.02,
             *           1.1,
             *           1.06,
             *           1,
             *           1.02,
             *           1,
             *           1.02,
             *           1.05,
             *           1.08,
             *           1.1,
             *           1.04,
             *           0.92,
             *           0.8,
             *           0.7,
             *           0.6
             *         ],
             *         "weekend_hourly_shape": [
             *           0.55,
             *           0.5,
             *           0.48,
             *           0.48,
             *           0.5,
             *           0.58,
             *           0.68,
             *           0.78,
             *           0.85,
             *           0.9,
             *           0.92,
             *           0.9,
             *           0.88,
             *           0.85,
             *           0.83,
             *           0.83,
             *           0.85,
             *           0.88,
             *           0.88,
             *           0.83,
             *           0.75,
             *           0.68,
             *           0.62,
             *           0.58
             *         ]
             *       },
             *       "deal": {
             *         "currency": "EUR",
             *         "discount_rate": 0.06,
             *         "end_date": "2036-12-31",
             *         "start_date": "2027-01-01"
             *       }
             *     }
             */
            config: components["schemas"]["PPAConfigSchema"];
            /**
             * Target Producer Npv
             * @default 0
             */
            target_producer_npv: number;
        };
        /** NegotiationRangeResponse */
        NegotiationRangeResponse: {
            /** Ranges */
            ranges: components["schemas"]["NegotiationRangeSchema"][];
        };
        /** NegotiationRangeSchema */
        NegotiationRangeSchema: {
            /** Supply Structure */
            supply_structure: string;
            producer_floor: components["schemas"]["SolverResultSchema"];
            consumer_ceiling: components["schemas"]["SolverResultSchema"];
            /** Midpoint */
            midpoint: number;
            /** Spread Eur Mwh */
            spread_eur_mwh: number;
        };
        /** PPAConfigSchema */
        PPAConfigSchema: {
            location?: components["schemas"]["LocationConfigSchema"];
            solar?: components["schemas"]["SolarConfigSchema"];
            market?: components["schemas"]["MarketPriceConfigSchema"];
            load?: components["schemas"]["ConsumerLoadConfigSchema"];
            deal?: components["schemas"]["DealConfigSchema"];
        };
        /** PathDistributionSchema */
        PathDistributionSchema: {
            /** Mean */
            mean: number;
            /** Std */
            std: number;
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
            /** Var 95 */
            var_95: number;
            /** Es 95 */
            es_95: number;
            /** Prob Negative */
            prob_negative: number;
        };
        /** PreviewResponse */
        PreviewResponse: {
            /** Solar Annual Yield Kwh Per Kwp */
            solar_annual_yield_kwh_per_kwp: number;
            /** Solar Total Gwh */
            solar_total_gwh: number;
            /** Avg Price Eur Mwh */
            avg_price_eur_mwh: number;
            /** Total Load Gwh */
            total_load_gwh: number;
            /** Hedge Ratio */
            hedge_ratio: number;
            /** Capture Rate */
            capture_rate: number;
            /** Sample Week Solar */
            sample_week_solar: components["schemas"]["TimeSeriesPoint"][];
            /** Sample Week Prices */
            sample_week_prices: components["schemas"]["TimeSeriesPoint"][];
            /** Sample Week Load */
            sample_week_load: components["schemas"]["TimeSeriesPoint"][];
        };
        /**
         * ProfilesResponse
         * @description Full-horizon raw hourly series (column-oriented).
         *
         *     All four lists have identical length (n_hours over the deal horizon).
         *     timestamps are ISO 8601 with timezone (Europe/Amsterdam).
         */
        ProfilesResponse: {
            /** Timestamps */
            timestamps: string[];
            /** Solar Mwh */
            solar_mwh: number[];
            /** Market Price Eur Mwh */
            market_price_eur_mwh: number[];
            /** Load Mwh */
            load_mwh: number[];
            /** N Hours */
            n_hours: number;
            /** Timezone */
            timezone: string;
        };
        /** RiskSummarySchema */
        RiskSummarySchema: {
            /** Combinations */
            combinations: components["schemas"]["ComboRiskSummarySchema"][];
            /** N Paths */
            n_paths: number;
            /** Base Strike */
            base_strike: number;
        };
        /** SimulationRequest */
        SimulationRequest: {
            /**
             * @default {
             *       "location": {
             *         "altitude": 10,
             *         "lat": 52.1,
             *         "lon": 5.1,
             *         "tz": "Europe/Amsterdam"
             *       },
             *       "solar": {
             *         "azimuth_deg": 180,
             *         "capacity_mw": 50,
             *         "cloud_factor_logit_scale": 0.7,
             *         "cloud_factor_phi": 0.9,
             *         "degradation_rate": 0.005,
             *         "monthly_cloud_means": [
             *           0.38,
             *           0.42,
             *           0.5,
             *           0.57,
             *           0.63,
             *           0.68,
             *           0.68,
             *           0.65,
             *           0.58,
             *           0.5,
             *           0.42,
             *           0.36
             *         ],
             *         "performance_ratio": 0.8,
             *         "seed": 42,
             *         "tilt_deg": 35
             *       },
             *       "market": {
             *         "ar1_phi": 0.7,
             *         "ar1_sigma": 8,
             *         "base_price": 83,
             *         "beta_wind_2027": 35,
             *         "beta_wind_2036": 75,
             *         "cannibalisation_alpha_2027": 40,
             *         "cannibalisation_alpha_2036": 60,
             *         "demand_peak_day": 15,
             *         "demand_weekday_shape": [
             *           -10,
             *           -12,
             *           -14,
             *           -14,
             *           -12,
             *           -10,
             *           -8,
             *           8,
             *           20,
             *           18,
             *           15,
             *           13,
             *           11,
             *           10,
             *           10,
             *           12,
             *           18,
             *           35,
             *           30,
             *           22,
             *           14,
             *           5,
             *           0,
             *           -8
             *         ],
             *         "demand_weekend_shape": [
             *           -12,
             *           -14,
             *           -16,
             *           -16,
             *           -14,
             *           -12,
             *           -10,
             *           -5,
             *           2,
             *           5,
             *           8,
             *           9,
             *           9,
             *           8,
             *           8,
             *           8,
             *           9,
             *           10,
             *           12,
             *           10,
             *           6,
             *           2,
             *           -2,
             *           -10
             *         ],
             *         "demand_winter_uplift": 0.15,
             *         "drift": -1.5,
             *         "monthly_wind_means": [
             *           0.42,
             *           0.4,
             *           0.38,
             *           0.33,
             *           0.28,
             *           0.25,
             *           0.24,
             *           0.25,
             *           0.3,
             *           0.36,
             *           0.4,
             *           0.43
             *         ],
             *         "production_cannibalisation_correlation": 0.65,
             *         "seasonal_amplitude": 15,
             *         "seasonal_peak_day": 15,
             *         "seed": 42,
             *         "system_solar_altitude": 10,
             *         "system_solar_azimuth_deg": 180,
             *         "system_solar_lat": 51.6,
             *         "system_solar_lon": 5.3,
             *         "system_solar_tilt_deg": 30,
             *         "system_solar_tz": "Europe/Amsterdam",
             *         "wind_cf_logit_scale": 0.6,
             *         "wind_cf_phi": 0.95,
             *         "wind_diurnal_logit_adder": [
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.08,
             *           0.05,
             *           0.02,
             *           -0.02,
             *           -0.05,
             *           -0.07,
             *           -0.09,
             *           -0.1,
             *           -0.1,
             *           -0.09,
             *           -0.07,
             *           -0.05,
             *           -0.02,
             *           0.02,
             *           0.05,
             *           0.07,
             *           0.08,
             *           0.1,
             *           0.1
             *         ],
             *         "wind_reference_cf": 0.33,
             *         "wind_seed": 43
             *       },
             *       "load": {
             *         "annual_consumption_gwh": 100,
             *         "noise_sigma": 0.05,
             *         "seasonal_amplitude": 0.15,
             *         "seasonal_peak_day": 15,
             *         "seed": 42,
             *         "weekday_hourly_shape": [
             *           0.55,
             *           0.5,
             *           0.48,
             *           0.48,
             *           0.52,
             *           0.62,
             *           0.78,
             *           0.9,
             *           0.98,
             *           1.02,
             *           1.1,
             *           1.06,
             *           1,
             *           1.02,
             *           1,
             *           1.02,
             *           1.05,
             *           1.08,
             *           1.1,
             *           1.04,
             *           0.92,
             *           0.8,
             *           0.7,
             *           0.6
             *         ],
             *         "weekend_hourly_shape": [
             *           0.55,
             *           0.5,
             *           0.48,
             *           0.48,
             *           0.5,
             *           0.58,
             *           0.68,
             *           0.78,
             *           0.85,
             *           0.9,
             *           0.92,
             *           0.9,
             *           0.88,
             *           0.85,
             *           0.83,
             *           0.83,
             *           0.85,
             *           0.88,
             *           0.88,
             *           0.83,
             *           0.75,
             *           0.68,
             *           0.62,
             *           0.58
             *         ]
             *       },
             *       "deal": {
             *         "currency": "EUR",
             *         "discount_rate": 0.06,
             *         "end_date": "2036-12-31",
             *         "start_date": "2027-01-01"
             *       }
             *     }
             */
            config: components["schemas"]["PPAConfigSchema"];
            /**
             * N Paths
             * @default 500
             */
            n_paths: number;
            /**
             * Base Strike
             * @default 65
             */
            base_strike: number;
            /**
             * Modes
             * @default [
             *       "joint",
             *       "price",
             *       "volume"
             *     ]
             */
            modes: ("joint" | "price" | "volume")[];
        };
        /** SolarConfigSchema */
        SolarConfigSchema: {
            /**
             * Capacity Mw
             * @default 50
             */
            capacity_mw: number;
            /**
             * Tilt Deg
             * @default 35
             */
            tilt_deg: number;
            /**
             * Azimuth Deg
             * @default 180
             */
            azimuth_deg: number;
            /**
             * Performance Ratio
             * @default 0.8
             */
            performance_ratio: number;
            /**
             * Degradation Rate
             * @default 0.005
             */
            degradation_rate: number;
            /**
             * Cloud Factor Phi
             * @default 0.9
             */
            cloud_factor_phi: number;
            /**
             * Cloud Factor Logit Scale
             * @default 0.7
             */
            cloud_factor_logit_scale: number;
            /**
             * Monthly Cloud Means
             * @default [
             *       0.38,
             *       0.42,
             *       0.5,
             *       0.57,
             *       0.63,
             *       0.68,
             *       0.68,
             *       0.65,
             *       0.58,
             *       0.5,
             *       0.42,
             *       0.36
             *     ]
             */
            monthly_cloud_means: number[];
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** SolverResultSchema */
        SolverResultSchema: {
            /** Strike Eur Mwh */
            strike_eur_mwh: number;
            /** Achieved Npv */
            achieved_npv: number;
            /** Target Npv */
            target_npv: number;
            /** N Iterations */
            n_iterations: number;
            /** Converged */
            converged: boolean;
            /** Supply Structure */
            supply_structure: string;
            /** Pricing Structure */
            pricing_structure: string;
        };
        /** TimeSeriesPoint */
        TimeSeriesPoint: {
            /** Timestamp */
            timestamp: string;
            /** Value */
            value: number;
        };
        /** TornadoEntrySchema */
        TornadoEntrySchema: {
            /** Parameter */
            parameter: string;
            /** Base Value */
            base_value: number;
            /** Low Value */
            low_value: number;
            /** High Value */
            high_value: number;
            /** Npv Base */
            npv_base: number;
            /** Npv Low */
            npv_low: number;
            /** Npv High */
            npv_high: number;
            /** Delta Npv Low */
            delta_npv_low: number;
            /** Delta Npv High */
            delta_npv_high: number;
            /** Abs Swing */
            abs_swing: number;
        };
        /** TornadoRequest */
        TornadoRequest: {
            /**
             * @default {
             *       "location": {
             *         "altitude": 10,
             *         "lat": 52.1,
             *         "lon": 5.1,
             *         "tz": "Europe/Amsterdam"
             *       },
             *       "solar": {
             *         "azimuth_deg": 180,
             *         "capacity_mw": 50,
             *         "cloud_factor_logit_scale": 0.7,
             *         "cloud_factor_phi": 0.9,
             *         "degradation_rate": 0.005,
             *         "monthly_cloud_means": [
             *           0.38,
             *           0.42,
             *           0.5,
             *           0.57,
             *           0.63,
             *           0.68,
             *           0.68,
             *           0.65,
             *           0.58,
             *           0.5,
             *           0.42,
             *           0.36
             *         ],
             *         "performance_ratio": 0.8,
             *         "seed": 42,
             *         "tilt_deg": 35
             *       },
             *       "market": {
             *         "ar1_phi": 0.7,
             *         "ar1_sigma": 8,
             *         "base_price": 83,
             *         "beta_wind_2027": 35,
             *         "beta_wind_2036": 75,
             *         "cannibalisation_alpha_2027": 40,
             *         "cannibalisation_alpha_2036": 60,
             *         "demand_peak_day": 15,
             *         "demand_weekday_shape": [
             *           -10,
             *           -12,
             *           -14,
             *           -14,
             *           -12,
             *           -10,
             *           -8,
             *           8,
             *           20,
             *           18,
             *           15,
             *           13,
             *           11,
             *           10,
             *           10,
             *           12,
             *           18,
             *           35,
             *           30,
             *           22,
             *           14,
             *           5,
             *           0,
             *           -8
             *         ],
             *         "demand_weekend_shape": [
             *           -12,
             *           -14,
             *           -16,
             *           -16,
             *           -14,
             *           -12,
             *           -10,
             *           -5,
             *           2,
             *           5,
             *           8,
             *           9,
             *           9,
             *           8,
             *           8,
             *           8,
             *           9,
             *           10,
             *           12,
             *           10,
             *           6,
             *           2,
             *           -2,
             *           -10
             *         ],
             *         "demand_winter_uplift": 0.15,
             *         "drift": -1.5,
             *         "monthly_wind_means": [
             *           0.42,
             *           0.4,
             *           0.38,
             *           0.33,
             *           0.28,
             *           0.25,
             *           0.24,
             *           0.25,
             *           0.3,
             *           0.36,
             *           0.4,
             *           0.43
             *         ],
             *         "production_cannibalisation_correlation": 0.65,
             *         "seasonal_amplitude": 15,
             *         "seasonal_peak_day": 15,
             *         "seed": 42,
             *         "system_solar_altitude": 10,
             *         "system_solar_azimuth_deg": 180,
             *         "system_solar_lat": 51.6,
             *         "system_solar_lon": 5.3,
             *         "system_solar_tilt_deg": 30,
             *         "system_solar_tz": "Europe/Amsterdam",
             *         "wind_cf_logit_scale": 0.6,
             *         "wind_cf_phi": 0.95,
             *         "wind_diurnal_logit_adder": [
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.08,
             *           0.05,
             *           0.02,
             *           -0.02,
             *           -0.05,
             *           -0.07,
             *           -0.09,
             *           -0.1,
             *           -0.1,
             *           -0.09,
             *           -0.07,
             *           -0.05,
             *           -0.02,
             *           0.02,
             *           0.05,
             *           0.07,
             *           0.08,
             *           0.1,
             *           0.1
             *         ],
             *         "wind_reference_cf": 0.33,
             *         "wind_seed": 43
             *       },
             *       "load": {
             *         "annual_consumption_gwh": 100,
             *         "noise_sigma": 0.05,
             *         "seasonal_amplitude": 0.15,
             *         "seasonal_peak_day": 15,
             *         "seed": 42,
             *         "weekday_hourly_shape": [
             *           0.55,
             *           0.5,
             *           0.48,
             *           0.48,
             *           0.52,
             *           0.62,
             *           0.78,
             *           0.9,
             *           0.98,
             *           1.02,
             *           1.1,
             *           1.06,
             *           1,
             *           1.02,
             *           1,
             *           1.02,
             *           1.05,
             *           1.08,
             *           1.1,
             *           1.04,
             *           0.92,
             *           0.8,
             *           0.7,
             *           0.6
             *         ],
             *         "weekend_hourly_shape": [
             *           0.55,
             *           0.5,
             *           0.48,
             *           0.48,
             *           0.5,
             *           0.58,
             *           0.68,
             *           0.78,
             *           0.85,
             *           0.9,
             *           0.92,
             *           0.9,
             *           0.88,
             *           0.85,
             *           0.83,
             *           0.83,
             *           0.85,
             *           0.88,
             *           0.88,
             *           0.83,
             *           0.75,
             *           0.68,
             *           0.62,
             *           0.58
             *         ]
             *       },
             *       "deal": {
             *         "currency": "EUR",
             *         "discount_rate": 0.06,
             *         "end_date": "2036-12-31",
             *         "start_date": "2027-01-01"
             *       }
             *     }
             */
            config: components["schemas"]["PPAConfigSchema"];
            /**
             * Supply Structure
             * @default pay_as_produced
             * @enum {string}
             */
            supply_structure: "pay_as_produced" | "pay_as_nominated" | "baseload";
            /**
             * Pricing Structure
             * @default fixed_flat
             * @enum {string}
             */
            pricing_structure: "fixed_flat" | "fixed_escalated" | "indexed_with_floor_cap" | "floating";
            /**
             * Base Strike
             * @default 65
             */
            base_strike: number;
        };
        /** TornadoResultSchema */
        TornadoResultSchema: {
            /** Entries */
            entries: components["schemas"]["TornadoEntrySchema"][];
            /** Supply Structure */
            supply_structure: string;
            /** Pricing Structure */
            pricing_structure: string;
            /** Base Strike */
            base_strike: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValuationMatrixRequest */
        ValuationMatrixRequest: {
            /**
             * @default {
             *       "location": {
             *         "altitude": 10,
             *         "lat": 52.1,
             *         "lon": 5.1,
             *         "tz": "Europe/Amsterdam"
             *       },
             *       "solar": {
             *         "azimuth_deg": 180,
             *         "capacity_mw": 50,
             *         "cloud_factor_logit_scale": 0.7,
             *         "cloud_factor_phi": 0.9,
             *         "degradation_rate": 0.005,
             *         "monthly_cloud_means": [
             *           0.38,
             *           0.42,
             *           0.5,
             *           0.57,
             *           0.63,
             *           0.68,
             *           0.68,
             *           0.65,
             *           0.58,
             *           0.5,
             *           0.42,
             *           0.36
             *         ],
             *         "performance_ratio": 0.8,
             *         "seed": 42,
             *         "tilt_deg": 35
             *       },
             *       "market": {
             *         "ar1_phi": 0.7,
             *         "ar1_sigma": 8,
             *         "base_price": 83,
             *         "beta_wind_2027": 35,
             *         "beta_wind_2036": 75,
             *         "cannibalisation_alpha_2027": 40,
             *         "cannibalisation_alpha_2036": 60,
             *         "demand_peak_day": 15,
             *         "demand_weekday_shape": [
             *           -10,
             *           -12,
             *           -14,
             *           -14,
             *           -12,
             *           -10,
             *           -8,
             *           8,
             *           20,
             *           18,
             *           15,
             *           13,
             *           11,
             *           10,
             *           10,
             *           12,
             *           18,
             *           35,
             *           30,
             *           22,
             *           14,
             *           5,
             *           0,
             *           -8
             *         ],
             *         "demand_weekend_shape": [
             *           -12,
             *           -14,
             *           -16,
             *           -16,
             *           -14,
             *           -12,
             *           -10,
             *           -5,
             *           2,
             *           5,
             *           8,
             *           9,
             *           9,
             *           8,
             *           8,
             *           8,
             *           9,
             *           10,
             *           12,
             *           10,
             *           6,
             *           2,
             *           -2,
             *           -10
             *         ],
             *         "demand_winter_uplift": 0.15,
             *         "drift": -1.5,
             *         "monthly_wind_means": [
             *           0.42,
             *           0.4,
             *           0.38,
             *           0.33,
             *           0.28,
             *           0.25,
             *           0.24,
             *           0.25,
             *           0.3,
             *           0.36,
             *           0.4,
             *           0.43
             *         ],
             *         "production_cannibalisation_correlation": 0.65,
             *         "seasonal_amplitude": 15,
             *         "seasonal_peak_day": 15,
             *         "seed": 42,
             *         "system_solar_altitude": 10,
             *         "system_solar_azimuth_deg": 180,
             *         "system_solar_lat": 51.6,
             *         "system_solar_lon": 5.3,
             *         "system_solar_tilt_deg": 30,
             *         "system_solar_tz": "Europe/Amsterdam",
             *         "wind_cf_logit_scale": 0.6,
             *         "wind_cf_phi": 0.95,
             *         "wind_diurnal_logit_adder": [
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.1,
             *           0.08,
             *           0.05,
             *           0.02,
             *           -0.02,
             *           -0.05,
             *           -0.07,
             *           -0.09,
             *           -0.1,
             *           -0.1,
             *           -0.09,
             *           -0.07,
             *           -0.05,
             *           -0.02,
             *           0.02,
             *           0.05,
             *           0.07,
             *           0.08,
             *           0.1,
             *           0.1
             *         ],
             *         "wind_reference_cf": 0.33,
             *         "wind_seed": 43
             *       },
             *       "load": {
             *         "annual_consumption_gwh": 100,
             *         "noise_sigma": 0.05,
             *         "seasonal_amplitude": 0.15,
             *         "seasonal_peak_day": 15,
             *         "seed": 42,
             *         "weekday_hourly_shape": [
             *           0.55,
             *           0.5,
             *           0.48,
             *           0.48,
             *           0.52,
             *           0.62,
             *           0.78,
             *           0.9,
             *           0.98,
             *           1.02,
             *           1.1,
             *           1.06,
             *           1,
             *           1.02,
             *           1,
             *           1.02,
             *           1.05,
             *           1.08,
             *           1.1,
             *           1.04,
             *           0.92,
             *           0.8,
             *           0.7,
             *           0.6
             *         ],
             *         "weekend_hourly_shape": [
             *           0.55,
             *           0.5,
             *           0.48,
             *           0.48,
             *           0.5,
             *           0.58,
             *           0.68,
             *           0.78,
             *           0.85,
             *           0.9,
             *           0.92,
             *           0.9,
             *           0.88,
             *           0.85,
             *           0.83,
             *           0.83,
             *           0.85,
             *           0.88,
             *           0.88,
             *           0.83,
             *           0.75,
             *           0.68,
             *           0.62,
             *           0.58
             *         ]
             *       },
             *       "deal": {
             *         "currency": "EUR",
             *         "discount_rate": 0.06,
             *         "end_date": "2036-12-31",
             *         "start_date": "2027-01-01"
             *       }
             *     }
             */
            config: components["schemas"]["PPAConfigSchema"];
            /**
             * Base Strike
             * @default 65
             */
            base_strike: number;
        };
        /** ValuationMatrixResponse */
        ValuationMatrixResponse: {
            /** Rows */
            rows: components["schemas"]["ValuationRowSchema"][];
            /** Base Strike */
            base_strike: number;
        };
        /** ValuationRowSchema */
        ValuationRowSchema: {
            /** Supply Structure */
            supply_structure: string;
            /** Pricing Structure */
            pricing_structure: string;
            /** Producer Npv */
            producer_npv: number;
            /** Consumer Npv */
            consumer_npv: number;
            /** Total Volume Mwh */
            total_volume_mwh: number;
            /** Average Strike Eur Mwh */
            average_strike_eur_mwh: number;
            /** Capture Rate */
            capture_rate: number;
            /** Volume Value */
            volume_value: number;
            /** Profile Value */
            profile_value: number;
        };
        /** VarianceDecompositionSchema */
        VarianceDecompositionSchema: {
            /** Total Variance */
            total_variance: number;
            /** Price Share */
            price_share: number;
            /** Volume Share */
            volume_share: number;
            /** Interaction Share */
            interaction_share: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    config_defaults_api_config_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PPAConfigSchema"];
                };
            };
        };
    };
    config_validate_api_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PPAConfigSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PPAConfigSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    central_profiles_api_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PPAConfigSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_central_scenario_api_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PPAConfigSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    valuation_matrix_api_valuation_matrix_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValuationMatrixRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuationMatrixResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_simulation_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonteCarloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    negotiation_range_api_solver_negotiation_range_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NegotiationRangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationRangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tornado_api_solver_tornado_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TornadoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TornadoResultSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fair_strike_api_solver_fair_strike_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FairStrikeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FairStrikeResultSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
